[Template]
Tmpl.Title=Known Conflicts
Tmpl.Class=Misc
Tmpl.Entry=Folder Lock | Folder Lock
Tmpl.Entry=StrokeIt | StrokeIt
#Tmpl.Entry=AquaSnap 1.16.2 | {CF0C7CA1-9BDC-4660-9CF5-E44446D49725}
#Tmpl.Entry=avast! Antivirus | avast
#Tmpl.Entry=AVG Antivirus | AVG
#Tmpl.Entry=BitDefender Antivirus | BitDefender
#Tmpl.Entry=Blue Ridge Networks AppGuard 3.0.13.1 | {2C9B1E69-DD05-40F5-8378-056A117028F9}
#Tmpl.Entry=Comodo Antivirus | {4E9C1938-BDC8-4897-8368-9574F9AF83E3}
#Tmpl.Entry=Comodo GeekBuddy 4.19.131 | {266FA04F-F0FA-4F7A-AA1E-387A57F579F2}
#Tmpl.Entry=Dr. Web 9 | {937CFD3F-8BFB-4208-81CB-F5004CD7B000}
#Tmpl.Entry=Dr. Web Katana | {7599F709-61D5-44F1-996C-4DFEB1B855E0}
#Tmpl.Entry=iTunes | {FBEB98F8-64E4-4FA3-A15E-4A9F42FF962E}
#Tmpl.Entry=Kaspersky Total Security 16 | {77E7AE5C-181C-4CAF-ADBF-946F11C1CE26}
#Tmpl.Entry=Norton Security | NS
#Tmpl.Entry=Nuance Power PDF Advanced 1.0 | {BD71D245-1A8B-4FB3-83E4-74F77FB39267}
#Tmpl.Entry=Office 2016 Click-to-Run | {90160000-007E-0000-0000-0000000FF1CE}
#Tmpl.Entry=PC Tools Firewall Plus | PC Tools Firewall Plus
