[Template]
Tmpl.Title=Open COM infrastructure (host COM host mode)
Tmpl.Class=System
# COM host open mode: use the host COM catalog / epmapper / OLE endpoints
OpenIpcPath=*\BaseNamedObjects*\__ComCatalogCache__
OpenIpcPath=\RPC Control\epmapper
OpenIpcPath=\RPC Control\OLE*
OpenIpcPath=\RPC Control\LRPC*
